import LegalPage from "@/components/LegalPage"
import { LEGAL } from "@/lib/legal"

export const metadata = { title: "Terms — Lacrosse Grind" }

export default function TermsPage() {
  return (
    <LegalPage title="Terms of use">
      <p>
        {LEGAL.product} is run by {LEGAL.company}. Using it means agreeing to
        what is below. It is short on purpose.
      </p>

      <h2>Who may open an account</h2>
      <p>
        Adults. You must be 18 or over, and if the account is for a child you
        must be their parent or guardian. You are responsible for what happens
        under it, including anything the child does. Children do not create
        their own accounts.
      </p>

      <h2>What this is, and what it is not</h2>
      <p>
        A log for recording training and a game built around showing up. It is
        not coaching, not medical or health advice, and not a training
        programme. The challenges are generated by an AI model and are not
        reviewed by a person before you see them.
      </p>
      <p>
        <strong>
          Use your own judgement about whether any activity is safe and suitable
          for your child, and stop if it is not.
        </strong>{" "}
        You are responsible for their safety; we are not.
      </p>

      <h2>Your content</h2>
      <p>
        The lanes, check-ins and prize you create stay yours. You give us only
        the permission needed to store and show them back to you. You are
        responsible for what you upload, and for holding the rights to any photo
        you add.
      </p>

      <h2>Fair use</h2>
      <p>
        The service is free, so please do not make it expensive. Do not attempt
        to break, overload or probe it, do not use it to store anything unlawful
        or harmful, and do not automate access to it.
      </p>
      <p>
        Coach generations are capped per account and overall each day. Hitting a
        cap is not a fault — it is the app declining to spend more that day.
      </p>

      <h2>Availability</h2>
      <p>
        The service is provided as it is, with no promise that it will be
        available, uninterrupted, or free of faults, and no warranties of any
        kind. It may change or stop at any time. Keep your own record of
        anything you would be sorry to lose.
      </p>

      <h2>Ending it</h2>
      <p>
        You can delete your account at any time from the Account page, which
        removes everything immediately and permanently. We may suspend or remove
        an account that breaks these terms.
      </p>

      <h2>Liability</h2>
      <p>
        To the fullest extent the law allows, {LEGAL.company} is not liable for
        any indirect or consequential loss, for lost data, or for injury arising
        from activities recorded in or suggested by the app. Nothing here limits
        liability that cannot lawfully be limited.
      </p>

      <h2>Governing law</h2>
      <p>
        These terms are governed by the laws of {LEGAL.jurisdiction}, without
        regard to its conflict-of-law rules.
      </p>

      <h2>Changes</h2>
      <p>
        If these terms change in a way that matters, the effective date at the
        top changes with them. Continuing to use the app means accepting the
        new version.
      </p>

      <h2>Contact</h2>
      <p>
        <a href={`mailto:${LEGAL.contactEmail}`}>{LEGAL.contactEmail}</a>
      </p>
    </LegalPage>
  )
}
